name: Simple CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Установить Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Поставить всё нужное
      run: pip install flask pytest bandit
    
    - name: Проверить безопасность
      run: bandit -r src/
    
    - name: Запустить тесты
      run: python -m pytest tests/