name: Simple CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Установить Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Поставить всё нужное
      run: |
        pip install flask
        pip install flask-login
        pip install flask-sqlalchemy
        pip install pytest
        pip install bandit
    
    - name: Проверить безопасность
      run: bandit -r src/
    
    - name: Запустить тесты
      run: python -m pytest tests/